---
- name: create app directory
  become: true
  command: mkdir /home/ubuntu/udapeople

- name: copy artifact.tar.gz
  become: true
  copy:
      src: artifact.tar.gz
      dest: /home/ubuntu/udapeople/artifact.tar.gz
      owner: ubuntu
      group: ubuntu

- name: "prepare artifact.tar.gz"
  become: true
  shell: |
      args:
          executable: /bin/bash
      pwd
      cd /home/ubuntu/udapeople
      tar -xvf artifact.tar.gz
      rm -rf artifact.tar.gz

- name: "stop already running instances"
  become: true
  shell: |
      pm2 stop default
  ignore_errors: true

- name: deploy backend server
  become: true
  shell: |
      cd /home/ubuntu/udapeople
      pm2 start npm --no-automation --name "backend" -- run start
      