version: 2.1

jobs:
    hello:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                name: "Hello"
                command: |
                    echo "Hello from Bravin"
    
    build-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [frontend-build]
            - run:
                name: Build front-end
                command: |
                  cd frontend 
                  npm install 
                  npm run build 
            - save_cache:
                paths: [frontend/node_modules]
                key: frontend-build
    
    build-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [backend-build]
            - run:
                name: Back-end build
                command: |
                    cd backend
                    npm install
                    npm run webpack
            - save_cache:
                paths: [backend/node_modules]
                key: backend-build

workflows:
  progress:
      jobs:
          - hello
          - build-frontend
          - build-backend