version: 2.1

jobs:
    hello:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                name: "Hello"
                command: |
                    echo "Hello from Bravin"
    
    build-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [frontend-build]
            - run:
                name: Build front-end
                command: |
                  cd frontend 
                  npm install 
                  npm run build 
            - save_cache:
                paths: [frontend/node_modules]
                key: frontend-build
    
    build-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [backend-build]
            - run:
                name: Back-end build
                command: |
                    cd backend
                    npm install
                    npm run build
                    #npm run webpack
            - save_cache:
                paths: [backend/node_modules]
                key: backend-build

    test-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [frontend-test]
            - run:
                name: "Test Frontend"
                command: |
                    cd frontend
                    npm install
                    npm run test
    
    test-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys: [backend-test]
            - run:
                name: "Test Backend"
                command: |
                    cd backend
                    npm install
                    npm run test
    
    scan-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
           - checkout
           - restore_cache:
               keys: ["frontend-scan"]
           - run:
               name: "Scan frontend for vulnerabilities"
               command: |
                   cd frontend
                   npm install
                   # npm install oauth-sign@^0.9.0
                   npm audit fix --audit-level=critical --force
                   npm audit --audit-level=critical
    
    scan-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
           - checkout
           - restore_cache:
               keys: ["backend-scan"]
           - run:
               name: "Scan the backend for vulnerabilities"
               command: |
                   cd backend
                   npm install
                   # npm install oauth-sign@^0.9.0
                   npm audit fix --audit-level=critical
                   npm audit --audit-level=critical

workflows:
  progress:
      jobs:
          - hello
          - build-frontend
          - build-backend
          - test-frontend:
              requires: [build-frontend]
          - test-backend:
              requires: [build-backend]
          - scan-frontend:
              requires: [build-frontend]
          - scan-backend:
              requires: [build-backend]